name: Deploy VCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install --no-frozen-lockfile



      - name: Compilar aplicación (Build)
        run: pnpm run build

        env:
          NODE_OPTIONS: --openssl-legacy-provider
          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
          VUE_APP_FRONT_URL: ${{ secrets.VUE_APP_FRONT_URL }}


      - name: Desplegar a servidor por SCP
        uses: appleboy/scp-action@8a92fcdb1eb4ffbf538b2fa286739760aac8a95b # v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: ${{ secrets.PROJECT_PATH }}
          strip_components: 1

